### ISSUE TITLE
Contact/Interface Node Indexing starts at 0 for tdr -> gmsh

### ISSUE THREAD

**Issue by gluek** [devsim/tdr-convert#5]
When converting tdr to gmsh the node indexing for the interfaces/contacts (boundary_info elements) starts at 0, which should start at 1.

The following change in all_info.py fixes the issue for this case, but this might have side effects on the other conversion paths.
```
class BoundaryInfo:
    def __init__(self, elements):
        self.elements = elements[:] + 1
```

**Comment by tcaduser** [comment]
Thanks for your report.  Please update to the latest version 0.1.5 and let me know if this resolves your issue.

**Comment by gluek** [comment]
Updated to the latest version, issue is gone. Thanks!
